try:
    # print(num)
    # print(1/0)
    printt(1/0)

except Exception as result:
    print(result)